# Loads default set of integrations. Do not remove.
default_config:

homeassistant:
  name: Home
  latitude: !secret latitude
  longitude: !secret longitude
  elevation: !secret elevation
  unit_system: imperial
  currency: USD
  country: US
  language: en
  time_zone: "America/Chicago"
  external_url: "https://lot125.kirbytoso.xyz:8446"
  internal_url: "http://homeassistant.local:8123"
  allowlist_external_dirs:
    - "/tmp"
  allowlist_external_urls: []
  media_dirs:
    media: "/media"

# Configure ssl - cert comes from LetsEncrypt Addon
http:
  use_x_forwarded_for: true
  trusted_proxies:
    - 172.30.33.0/24
    - 127.0.0.1

# Load frontend themes from the themes folder
frontend:
  themes: !include_dir_merge_named themes

automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
mqtt: !include mqtt.yaml
o365: !include o365.yaml
python_script:

# # Proximity sensors for people presence cards
# proximity:
#   dale_home:
#     devices:
#       - device_tracker.sm_s918u
#     tolerance: 50
#     unit_of_measurement: mi
#   cc_home:
#     devices:
#       - device_tracker.iphone
#     tolerance: 50
#     unit_of_measurement: mi

# # History sensors
# sensor:
#   - platform: history_stats
#     name: Total cars counted
#     entity_id: counter.car_count
#     type: count
#     start: "{{ now().replace(hour=0, minute=0, second=0) }}"
#     end: "{{ now() }}"
#   - platform: history_stats
#     name: Total people counted
#     entity_id: counter.person_count
#     type: count
#     start: "{{ now().replace(hour=0, minute=0, second=0) }}"
#     end: "{{ now() }}"

# Notification groups
notify:
  - platform: group
    name: "Mobile devices"
    services:
      - service: mobile_app_iphone
      - service: mobile_app_sm_s918u

shell_command:
  delete_old_tts: 'find /root/config/tts/ -maxdepth 1 -type f -mtime +1 -name ''*.piper.mp3'' -exec rm {} -f \;'

lovelace:
  mode: storage
  dashboards: !include dashboards/dashboards.yaml
